// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_WFCMWyAvTWbvBYoPYWZyvIatrERfuLg',
    appId: '1:233925994799:web:ab3b69353de092b43119da',
    messagingSenderId: '233925994799',
    projectId: 'flutter-coffeina',
    authDomain: 'flutter-coffeina.firebaseapp.com',
    storageBucket: 'flutter-coffeina.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJXG1AabxVlyUKe7drCJQZUqTJdzm_cE',
    appId: '1:233925994799:android:61faf2681ece33843119da',
    messagingSenderId: '233925994799',
    projectId: 'flutter-coffeina',
    storageBucket: 'flutter-coffeina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfQYhVFh5ckUYq6fXp0sGircWrGZSrWA',
    appId: '1:233925994799:ios:4968a2efde1e5e963119da',
    messagingSenderId: '233925994799',
    projectId: 'flutter-coffeina',
    storageBucket: 'flutter-coffeina.appspot.com',
    iosClientId: '233925994799-6a1tpna2d4qhi4h5qmdoudmfn5jlbepp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfQYhVFh5ckUYq6fXp0sGircWrGZSrWA',
    appId: '1:233925994799:ios:8d883399532c511a3119da',
    messagingSenderId: '233925994799',
    projectId: 'flutter-coffeina',
    storageBucket: 'flutter-coffeina.appspot.com',
    iosClientId: '233925994799-e50gi7jj12baqbb1g8aig3ti0dlkil8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
