// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2QggR22zK9W66zSE5IjgA3etpk4DyEcY',
    appId: '1:1004140948967:web:cabc7af9028f3c26642142',
    messagingSenderId: '1004140948967',
    projectId: 'coffeina2-291a6',
    authDomain: 'coffeina2-291a6.firebaseapp.com',
    storageBucket: 'coffeina2-291a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7q5PrnfyZgefV6UNdMIWXQRiqO5erHZ4',
    appId: '1:1004140948967:android:a306b04e9b0b62bd642142',
    messagingSenderId: '1004140948967',
    projectId: 'coffeina2-291a6',
    storageBucket: 'coffeina2-291a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdJTabSUl44sQr5KKh1k0BShOMFg30aQ',
    appId: '1:1004140948967:ios:a86a67cca197edf8642142',
    messagingSenderId: '1004140948967',
    projectId: 'coffeina2-291a6',
    storageBucket: 'coffeina2-291a6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdJTabSUl44sQr5KKh1k0BShOMFg30aQ',
    appId: '1:1004140948967:ios:6988f246f7b81bd3642142',
    messagingSenderId: '1004140948967',
    projectId: 'coffeina2-291a6',
    storageBucket: 'coffeina2-291a6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
