// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0sFFu8OmZee-xw-D6-_WLDeZ1XVPBFoA',
    appId: '1:139447114651:web:a53ad127f5b2743ca25f3e',
    messagingSenderId: '139447114651',
    projectId: 'coffeina1-a5b31',
    authDomain: 'coffeina1-a5b31.firebaseapp.com',
    storageBucket: 'coffeina1-a5b31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPELsh0Oi3_RsLQO0sKFcJB9rhZ0a8HbU',
    appId: '1:139447114651:android:752b2138e77c8f79a25f3e',
    messagingSenderId: '139447114651',
    projectId: 'coffeina1-a5b31',
    storageBucket: 'coffeina1-a5b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODOqUfyivlygVhGWJCEgem6PwbzICbIs',
    appId: '1:139447114651:ios:5177d6bd42669cc8a25f3e',
    messagingSenderId: '139447114651',
    projectId: 'coffeina1-a5b31',
    storageBucket: 'coffeina1-a5b31.appspot.com',
    iosClientId: '139447114651-dbflnued7lkptv87teg1vcbqpo342cpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODOqUfyivlygVhGWJCEgem6PwbzICbIs',
    appId: '1:139447114651:ios:d6aa7ed716f41c95a25f3e',
    messagingSenderId: '139447114651',
    projectId: 'coffeina1-a5b31',
    storageBucket: 'coffeina1-a5b31.appspot.com',
    iosClientId: '139447114651-j176rb1mpjhrm72d3bgg601ptshjlgs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
